module.exports = [
"[project]/src/app/icon.svg.mjs { IMAGE => \"[project]/src/app/icon.svg (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/icon.svg.mjs { IMAGE => \"[project]/src/app/icon.svg (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/not-found.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/browse/search/SearchResultsContent.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/app/browse/search/SearchResultsContent.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/app/browse/search/SearchResultsContent.tsx <module evaluation>", "default");
}),
"[project]/src/app/browse/search/SearchResultsContent.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
// This file is generated by next-core EcmascriptClientReferenceModule.
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/app/browse/search/SearchResultsContent.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/app/browse/search/SearchResultsContent.tsx", "default");
}),
"[project]/src/app/browse/search/SearchResultsContent.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$browse$2f$search$2f$SearchResultsContent$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/app/browse/search/SearchResultsContent.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$browse$2f$search$2f$SearchResultsContent$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/app/browse/search/SearchResultsContent.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$browse$2f$search$2f$SearchResultsContent$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/lib/api/tmdb-client.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

// --- Streaming Providers Types ---
__turbopack_context__.s([
    "getAiringNowAnimeShows",
    ()=>getAiringNowAnimeShows,
    "getAiringNowCartoons",
    ()=>getAiringNowCartoons,
    "getAiringNowKDramas",
    ()=>getAiringNowKDramas,
    "getAiringNowShows",
    ()=>getAiringNowShows,
    "getAiringTodayShows",
    ()=>getAiringTodayShows,
    "getClassicAnimeShows",
    ()=>getClassicAnimeShows,
    "getCollectionDetails",
    ()=>getCollectionDetails,
    "getFamilyCartoonShows",
    ()=>getFamilyCartoonShows,
    "getImageUrl",
    ()=>getImageUrl,
    "getKidsFavoriteCartoons",
    ()=>getKidsFavoriteCartoons,
    "getMovieCredits",
    ()=>getMovieCredits,
    "getMovieDetails",
    ()=>getMovieDetails,
    "getMovieTrailers",
    ()=>getMovieTrailers,
    "getMovieWatchProviders",
    ()=>getMovieWatchProviders,
    "getMoviesByGenre",
    ()=>getMoviesByGenre,
    "getNewReleases",
    ()=>getNewReleases,
    "getPopularAnimeShows",
    ()=>getPopularAnimeShows,
    "getPopularCartoonShows",
    ()=>getPopularCartoonShows,
    "getPopularMovies",
    ()=>getPopularMovies,
    "getPopularTVShows",
    ()=>getPopularTVShows,
    "getSeasonDetails",
    ()=>getSeasonDetails,
    "getSimilarMovies",
    ()=>getSimilarMovies,
    "getSimilarTVShows",
    ()=>getSimilarTVShows,
    "getTVCredits",
    ()=>getTVCredits,
    "getTVShowDetails",
    ()=>getTVShowDetails,
    "getTVShowsByGenre",
    ()=>getTVShowsByGenre,
    "getTVTrailers",
    ()=>getTVTrailers,
    "getTVWatchProviders",
    ()=>getTVWatchProviders,
    "getTopRatedAnimeShows",
    ()=>getTopRatedAnimeShows,
    "getTopRatedCartoonShows",
    ()=>getTopRatedCartoonShows,
    "getTopRatedKDramas",
    ()=>getTopRatedKDramas,
    "getTopRatedMovies",
    ()=>getTopRatedMovies,
    "getTopRatedShows",
    ()=>getTopRatedShows,
    "getTrendingCartoons",
    ()=>getTrendingCartoons,
    "getTrendingMovies",
    ()=>getTrendingMovies,
    "getTrendingTVShows",
    ()=>getTrendingTVShows,
    "getUpcomingAnimeShows",
    ()=>getUpcomingAnimeShows,
    "getUpcomingCartoons",
    ()=>getUpcomingCartoons,
    "getUpcomingKDramas",
    ()=>getUpcomingKDramas,
    "getUpcomingMovies",
    ()=>getUpcomingMovies,
    "getUpcomingShows",
    ()=>getUpcomingShows,
    "searchTitles",
    ()=>searchTitles
]);
async function getMovieWatchProviders(movieId, country = 'US') {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/movie/${movieId}/watch/providers?api_key=${TMDB_API_KEY}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error(`Failed to fetch movie watch providers: ${response.status}`);
        }
        const data = await response.json();
        return data.results?.[country] ?? null;
    } catch (error) {
        console.error('Error fetching movie watch providers:', error);
        return null;
    }
}
async function getTVWatchProviders(tvId, country = 'US') {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/tv/${tvId}/watch/providers?api_key=${TMDB_API_KEY}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error(`Failed to fetch TV watch providers: ${response.status}`);
        }
        const data = await response.json();
        return data.results?.[country] ?? null;
    } catch (error) {
        console.error('Error fetching TV watch providers:', error);
        return null;
    }
}
const TMDB_API_KEY = process.env.TMDB_API_KEY;
const TMDB_BASE_URL = 'https://api.themoviedb.org/3';
const TMDB_IMAGE_BASE_URL = 'https://image.tmdb.org/t/p';
async function getNewReleases(page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/movie/now_playing?api_key=${TMDB_API_KEY}&language=en-US&page=${page}`, {
            next: {
                revalidate: 86400
            }
        } // Cache for 24 hours (daily refresh)
        );
        if (!response.ok) {
            throw new Error('Failed to fetch movies');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error fetching new releases:', error);
        return [];
    }
}
async function getTrendingMovies(page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/trending/movie/week?api_key=${TMDB_API_KEY}&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch trending movies');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error fetching trending movies:', error);
        return [];
    }
}
async function getTopRatedMovies(page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/movie/top_rated?api_key=${TMDB_API_KEY}&language=en-US&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch top rated movies');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error fetching top rated movies:', error);
        return [];
    }
}
async function getPopularMovies(page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/movie/popular?api_key=${TMDB_API_KEY}&language=en-US&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch popular movies');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error fetching popular movies:', error);
        return [];
    }
}
async function getPopularTVShows(page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/tv/popular?api_key=${TMDB_API_KEY}&language=en-US&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch TV shows');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error fetching TV shows:', error);
        return [];
    }
}
async function getTrendingTVShows(page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/trending/tv/week?api_key=${TMDB_API_KEY}&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch trending TV shows');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error fetching trending TV shows:', error);
        return [];
    }
}
async function getTopRatedShows(page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/tv/top_rated?api_key=${TMDB_API_KEY}&language=en-US&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch top rated shows');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error fetching top rated shows:', error);
        return [];
    }
}
async function getUpcomingShows(page = 1) {
    try {
        const today = new Date().toISOString().split('T')[0];
        const futureDate = new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
        const response = await fetch(`${TMDB_BASE_URL}/discover/tv?api_key=${TMDB_API_KEY}&language=en-US&sort_by=first_air_date.desc&first_air_date.gte=${today}&first_air_date.lte=${futureDate}&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch upcoming shows');
        }
        const data = await response.json();
        // Filter to only include shows with first_air_date in the future
        return data.results.filter((show)=>show.first_air_date && new Date(show.first_air_date) >= new Date(today));
    } catch (error) {
        console.error('Error fetching upcoming shows:', error);
        return [];
    }
}
async function getAiringTodayShows(page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/tv/airing_today?api_key=${TMDB_API_KEY}&language=en-US&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch shows airing today');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error fetching airing today shows:', error);
        return [];
    }
}
async function getAiringNowShows(page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/tv/on_the_air?api_key=${TMDB_API_KEY}&language=en-US&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch shows on the air');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error fetching on the air shows:', error);
        return [];
    }
}
async function getUpcomingMovies(page = 1) {
    try {
        const today = new Date().toISOString().split('T')[0];
        const response = await fetch(`${TMDB_BASE_URL}/movie/upcoming?api_key=${TMDB_API_KEY}&language=en-US&region=US&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch upcoming movies');
        }
        const data = await response.json();
        // Filter to only include movies with release_date in the future
        return data.results.filter((movie)=>movie.release_date && new Date(movie.release_date) >= new Date(today));
    } catch (error) {
        console.error('Error fetching upcoming movies:', error);
        return [];
    }
}
function getImageUrl(path, size = 'original') {
    if (!path) return '/placeholder-movie.jpg';
    return `${TMDB_IMAGE_BASE_URL}/${size}${path}`;
}
async function getMovieDetails(movieId) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/movie/${movieId}?api_key=${TMDB_API_KEY}&language=en-US`, {
            next: {
                revalidate: 3600
            }
        });
        if (response.status === 404) {
            return null;
        }
        if (!response.ok) {
            throw new Error(`Failed to fetch movie details: ${response.status}`);
        }
        return await response.json();
    } catch (error) {
        console.error('Error fetching movie details:', error);
        return null;
    }
}
async function getTVShowDetails(tvId) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/tv/${tvId}?api_key=${TMDB_API_KEY}&language=en-US`, {
            next: {
                revalidate: 3600
            }
        });
        if (response.status === 404) {
            return null;
        }
        if (!response.ok) {
            throw new Error(`Failed to fetch TV show details: ${response.status}`);
        }
        return await response.json();
    } catch (error) {
        console.error('Error fetching TV show details:', error);
        return null;
    }
}
async function getMovieCredits(movieId) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/movie/${movieId}/credits?api_key=${TMDB_API_KEY}&language=en-US`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error(`Failed to fetch movie credits: ${response.status}`);
        }
        const data = await response.json();
        return Array.isArray(data.cast) ? data.cast : [];
    } catch (error) {
        console.error('Error fetching movie credits:', error);
        return [];
    }
}
async function getTVCredits(tvId) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/tv/${tvId}/credits?api_key=${TMDB_API_KEY}&language=en-US`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error(`Failed to fetch TV credits: ${response.status}`);
        }
        const data = await response.json();
        return Array.isArray(data.cast) ? data.cast : [];
    } catch (error) {
        console.error('Error fetching TV credits:', error);
        return [];
    }
}
const MAX_TRAILER_FAILURES = 3;
let movieTrailerFailureCount = 0;
let tvTrailerFailureCount = 0;
async function getMovieTrailers(movieId) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/movie/${movieId}/videos?api_key=${TMDB_API_KEY}&language=en-US`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error(`API error: ${response.status} ${response.statusText}`);
        }
        const data = await response.json();
        if (!data.results || !Array.isArray(data.results)) {
            return [];
        }
        const videos = data.results.filter((video)=>video.site === 'YouTube');
        const teasers = videos.filter((video)=>video.type === 'Teaser' || video.name?.toLowerCase().includes('teaser'));
        return teasers.length > 0 ? teasers : videos;
    } catch (error) {
        movieTrailerFailureCount += 1;
        // if (movieTrailerFailureCount >= MAX_TRAILER_FAILURES) {
        //   movieTrailerFetchDisabled = true;
        // }
        console.error('Error fetching movie trailers:', error);
        return [];
    }
}
async function getTVTrailers(tvId) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/tv/${tvId}/videos?api_key=${TMDB_API_KEY}&language=en-US`, {
            next: {
                revalidate: 3600
            }
        });
        if (response.status === 404) {
            // TV show or videos not found, return empty array gracefully
            return [];
        }
        if (!response.ok) {
            throw new Error(`API error: ${response.status} ${response.statusText}`);
        }
        const data = await response.json();
        if (!data.results || !Array.isArray(data.results)) {
            return [];
        }
        const videos = data.results.filter((video)=>video.site === 'YouTube');
        const teasers = videos.filter((video)=>video.type === 'Teaser' || video.name?.toLowerCase().includes('teaser'));
        return teasers.length > 0 ? teasers : videos;
    } catch (error) {
        tvTrailerFailureCount += 1;
        // if (tvTrailerFailureCount >= MAX_TRAILER_FAILURES) {
        //   tvTrailerFetchDisabled = true;
        // }
        console.error('Error fetching TV trailers:', error);
        return [];
    }
}
async function getMoviesByGenre(genreId, page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/discover/movie?api_key=${TMDB_API_KEY}&language=en-US&with_genres=${genreId}&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch movies by genre');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error fetching movies by genre:', error);
        return [];
    }
}
async function getTVShowsByGenre(genreId, page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/discover/tv?api_key=${TMDB_API_KEY}&language=en-US&with_genres=${genreId}&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to fetch TV shows by genre');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error fetching TV shows by genre:', error);
        return [];
    }
}
function formatDate(date) {
    return date.toISOString().split('T')[0];
}
async function discoverAnimationShows(params) {
    try {
        const searchParams = new URLSearchParams();
        searchParams.set('api_key', TMDB_API_KEY ?? '');
        searchParams.set('language', 'en-US');
        searchParams.set('page', params.page ?? '1');
        searchParams.set('include_adult', 'false');
        searchParams.set('include_null_first_air_dates', 'false');
        Object.entries(params).forEach(([key, value])=>{
            if (value) {
                searchParams.set(key, value);
            }
        });
        const response = await fetch(`${TMDB_BASE_URL}/discover/tv?${searchParams.toString()}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to discover animation shows');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error discovering animation shows:', error);
        return [];
    }
}
async function getAnimationChart({ chart, originalLanguage, includeKids, page = 1 }) {
    const baseParams = {
        sort_by: 'popularity.desc',
        'with_genres': includeKids ? '16,10762' : '16',
        page: page.toString(),
        'with_original_language': originalLanguage
    };
    switch(chart){
        case 'popular':
            baseParams.sort_by = 'popularity.desc';
            break;
        case 'topRated':
            baseParams.sort_by = 'vote_average.desc';
            baseParams['vote_count.gte'] = '200';
            break;
        case 'airingNow':
            baseParams.sort_by = 'popularity.desc';
            baseParams['first_air_date.lte'] = formatDate(new Date());
            baseParams['first_air_date.gte'] = formatDate(new Date(Date.now() - 365 * 24 * 60 * 60 * 1000));
            break;
        case 'upcoming':
            baseParams.sort_by = 'popularity.desc';
            baseParams['first_air_date.gte'] = formatDate(new Date());
            break;
        case 'classics':
            baseParams.sort_by = 'vote_average.desc';
            baseParams['vote_count.gte'] = '500';
            const tenYearsAgo = new Date();
            tenYearsAgo.setFullYear(tenYearsAgo.getFullYear() - 10);
            baseParams['first_air_date.lte'] = formatDate(tenYearsAgo);
            break;
        case 'trending':
            baseParams.sort_by = 'popularity.desc';
            baseParams['first_air_date.gte'] = formatDate(new Date(Date.now() - 365 * 24 * 60 * 60 * 1000));
            break;
        case 'family':
            baseParams.sort_by = 'vote_average.desc';
            baseParams['vote_count.gte'] = '100';
            break;
        case 'kids':
            baseParams.sort_by = 'popularity.desc';
            baseParams['vote_count.gte'] = '50';
            break;
    }
    return discoverAnimationShows(baseParams);
}
async function getPopularAnimeShows(page = 1) {
    return getAnimationChart({
        chart: 'popular',
        originalLanguage: 'ja',
        page
    });
}
async function getTopRatedAnimeShows(page = 1) {
    return getAnimationChart({
        chart: 'topRated',
        originalLanguage: 'ja',
        page
    });
}
async function getAiringNowAnimeShows(page = 1) {
    return getAnimationChart({
        chart: 'airingNow',
        originalLanguage: 'ja',
        page
    });
}
async function getUpcomingAnimeShows(page = 1) {
    return getAnimationChart({
        chart: 'upcoming',
        originalLanguage: 'ja',
        page
    });
}
async function getClassicAnimeShows(page = 1) {
    return getAnimationChart({
        chart: 'classics',
        originalLanguage: 'ja',
        page
    });
}
async function getPopularCartoonShows(page = 1) {
    return getAnimationChart({
        chart: 'popular',
        originalLanguage: 'en',
        includeKids: true,
        page
    });
}
async function getTopRatedCartoonShows(page = 1) {
    return getAnimationChart({
        chart: 'topRated',
        originalLanguage: 'en',
        includeKids: true,
        page
    });
}
async function getKidsFavoriteCartoons(page = 1) {
    return getAnimationChart({
        chart: 'kids',
        originalLanguage: 'en',
        includeKids: true,
        page
    });
}
async function getTrendingCartoons(page = 1) {
    return getAnimationChart({
        chart: 'trending',
        originalLanguage: 'en',
        includeKids: true,
        page
    });
}
async function getUpcomingCartoons(page = 1) {
    return getAnimationChart({
        chart: 'upcoming',
        originalLanguage: 'en',
        includeKids: true,
        page
    });
}
async function getAiringNowCartoons(page = 1) {
    return getAnimationChart({
        chart: 'airingNow',
        originalLanguage: 'en',
        includeKids: true,
        page
    });
}
async function getFamilyCartoonShows(page = 1) {
    return getAnimationChart({
        chart: 'family',
        originalLanguage: 'en',
        includeKids: true,
        page
    });
}
async function getKDramaChart({ chart, page = 1 }) {
    try {
        const searchParams = new URLSearchParams();
        searchParams.set('api_key', TMDB_API_KEY ?? '');
        searchParams.set('language', 'en-US');
        searchParams.set('page', page.toString());
        searchParams.set('include_adult', 'false');
        searchParams.set('include_null_first_air_dates', 'false');
        searchParams.set('with_genres', '18'); // Drama genre ID
        searchParams.set('with_origin_country', 'KR'); // South Korea
        searchParams.set('sort_by', chart === 'topRated' ? 'vote_average.desc' : 'first_air_date.desc');
        if (chart === 'topRated') {
            searchParams.set('vote_count.gte', '100');
        } else if (chart === 'upcoming') {
            const today = formatDate(new Date());
            searchParams.set('first_air_date.gte', today);
        } else if (chart === 'airingNow') {
            const today = formatDate(new Date());
            searchParams.set('first_air_date.lte', today);
            searchParams.set('first_air_date.gte', formatDate(new Date(Date.now() - 365 * 24 * 60 * 60 * 1000)));
        }
        const response = await fetch(`${TMDB_BASE_URL}/discover/tv?${searchParams.toString()}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error('Failed to discover K dramas');
        }
        const data = await response.json();
        return data.results;
    } catch (error) {
        console.error('Error discovering K dramas:', error);
        return [];
    }
}
async function getTopRatedKDramas(page = 1) {
    return getKDramaChart({
        chart: 'topRated',
        page
    });
}
async function getAiringNowKDramas(page = 1) {
    return getKDramaChart({
        chart: 'airingNow',
        page
    });
}
async function getUpcomingKDramas(page = 1) {
    return getKDramaChart({
        chart: 'upcoming',
        page
    });
}
function normalizeString(value) {
    return value ?? '';
}
function normalizeNumber(value) {
    return Number.isFinite(value) ? Number(value) : 0;
}
async function searchTitles(query, page = 1) {
    const trimmedQuery = query.trim();
    if (!trimmedQuery) {
        return [];
    }
    try {
        const url = new URL(`${TMDB_BASE_URL}/search/multi`);
        url.searchParams.set('api_key', TMDB_API_KEY ?? '');
        url.searchParams.set('query', trimmedQuery);
        url.searchParams.set('language', 'en-US');
        url.searchParams.set('page', page.toString());
        url.searchParams.set('include_adult', 'false');
        const response = await fetch(url.toString(), {
            cache: 'no-store'
        });
        if (!response.ok) {
            throw new Error(`Failed to search titles: ${response.status}`);
        }
        const data = await response.json();
        const results = Array.isArray(data.results) ? data.results : [];
        return results.filter((item)=>(item.media_type === 'movie' || item.media_type === 'tv') && item.id).map((item)=>{
            if (item.media_type === 'movie') {
                const movie = {
                    id: item.id,
                    title: normalizeString(item.title || item.name || 'Untitled'),
                    overview: normalizeString(item.overview),
                    backdrop_path: normalizeString(item.backdrop_path),
                    poster_path: normalizeString(item.poster_path),
                    release_date: normalizeString(item.release_date),
                    vote_average: normalizeNumber(item.vote_average),
                    popularity: 0,
                    genre_ids: item.genre_ids ?? [],
                    original_language: item.original_language
                };
                return movie;
            }
            const tvShow = {
                id: item.id,
                name: normalizeString(item.name || item.title || 'Untitled'),
                overview: normalizeString(item.overview),
                backdrop_path: normalizeString(item.backdrop_path),
                poster_path: normalizeString(item.poster_path),
                first_air_date: normalizeString(item.first_air_date),
                vote_average: normalizeNumber(item.vote_average),
                popularity: 0,
                genre_ids: item.genre_ids ?? [],
                original_language: item.original_language,
                origin_country: item.origin_country ?? []
            };
            return tvShow;
        });
    } catch (error) {
        console.error('Error searching titles:', error);
        return [];
    }
}
async function getSimilarMovies(movieId, page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/movie/${movieId}/similar?api_key=${TMDB_API_KEY}&language=en-US&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error(`Failed to fetch similar movies: ${response.status}`);
        }
        const data = await response.json();
        return Array.isArray(data.results) ? data.results : [];
    } catch (error) {
        console.error('Error fetching similar movies:', error);
        return [];
    }
}
async function getSimilarTVShows(tvId, page = 1) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/tv/${tvId}/similar?api_key=${TMDB_API_KEY}&language=en-US&page=${page}`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error(`Failed to fetch similar TV shows: ${response.status}`);
        }
        const data = await response.json();
        return Array.isArray(data.results) ? data.results : [];
    } catch (error) {
        console.error('Error fetching similar TV shows:', error);
        return [];
    }
}
async function getCollectionDetails(collectionId) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/collection/${collectionId}?api_key=${TMDB_API_KEY}&language=en-US`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error(`Failed to fetch collection details: ${response.status}`);
        }
        const data = await response.json();
        return data;
    } catch (error) {
        console.error('Error fetching collection details:', error);
        return null;
    }
}
async function getSeasonDetails(tvId, seasonNumber) {
    try {
        const response = await fetch(`${TMDB_BASE_URL}/tv/${tvId}/season/${seasonNumber}?api_key=${TMDB_API_KEY}&language=en-US`, {
            next: {
                revalidate: 3600
            }
        });
        if (!response.ok) {
            throw new Error(`Failed to fetch season details: ${response.status}`);
        }
        const data = await response.json();
        return data;
    } catch (error) {
        console.error('Error fetching season details:', error);
        return null;
    }
}
}),
"[project]/src/lib/constants/genres.const.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "animeCharts",
    ()=>animeCharts,
    "animeGenreIds",
    ()=>animeGenreIds,
    "animeGenres",
    ()=>animeGenres,
    "cartoonCharts",
    ()=>cartoonCharts,
    "cartoonGenreIds",
    ()=>cartoonGenreIds,
    "cartoonGenres",
    ()=>cartoonGenres,
    "movieCharts",
    ()=>movieCharts,
    "movieGenreIds",
    ()=>movieGenreIds,
    "movieGenres",
    ()=>movieGenres,
    "tvCharts",
    ()=>tvCharts,
    "tvGenreIds",
    ()=>tvGenreIds,
    "tvGenres",
    ()=>tvGenres
]);
const movieGenres = [
    "Action",
    "Adventure",
    "Animation",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "History",
    "Horror",
    "Music",
    "Mystery",
    "Romance",
    "Science Fiction",
    "TV Movie",
    "Thriller",
    "War",
    "Western"
];
const tvGenres = [
    "Action & Adventure",
    "Animation",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Kids",
    "Mystery",
    "News",
    "Reality",
    "Sci-Fi & Fantasy",
    "Soap",
    "Talk",
    "War & Politics",
    "Western"
];
const animeGenres = [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Fantasy",
    "Horror",
    "Magic",
    "Mystery",
    "Psychological",
    "Romance",
    "School",
    "Science Fiction",
    "Shounen",
    "Shoujo",
    "Seinen",
    "Supernatural",
    "Thriller"
];
const cartoonGenres = [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Family",
    "Fantasy",
    "Kids",
    "Mystery",
    "Science Fiction"
];
const movieGenreIds = {
    "Action": 28,
    "Adventure": 12,
    "Animation": 16,
    "Comedy": 35,
    "Crime": 80,
    "Documentary": 99,
    "Drama": 18,
    "Family": 10751,
    "Fantasy": 14,
    "History": 36,
    "Horror": 27,
    "Music": 10402,
    "Mystery": 9648,
    "Romance": 10749,
    "Science Fiction": 878,
    "TV Movie": 10770,
    "Thriller": 53,
    "War": 10752,
    "Western": 37
};
const tvGenreIds = {
    "Action & Adventure": 10759,
    "Animation": 16,
    "Comedy": 35,
    "Crime": 80,
    "Documentary": 99,
    "Drama": 18,
    "Family": 10751,
    "Kids": 10762,
    "Mystery": 9648,
    "News": 10763,
    "Reality": 10764,
    "Sci-Fi & Fantasy": 10765,
    "Soap": 10766,
    "Talk": 10767,
    "War & Politics": 10768,
    "Western": 37
};
const animeGenreIds = {
    "Action": 28,
    "Adventure": 12,
    "Comedy": 35,
    "Drama": 18,
    "Fantasy": 14,
    "Horror": 27,
    "Magic": 10749,
    "Mystery": 9648,
    "Psychological": 9648,
    "Romance": 10749,
    "School": 10751,
    "Science Fiction": 878,
    "Shounen": 35,
    "Shoujo": 10749,
    "Seinen": 18,
    "Supernatural": 14,
    "Thriller": 53
};
const cartoonGenreIds = {
    "Action": 28,
    "Adventure": 12,
    "Comedy": 35,
    "Drama": 18,
    "Family": 10751,
    "Fantasy": 14,
    "Kids": 10762,
    "Mystery": 9648,
    "Science Fiction": 878
};
const movieCharts = [
    "Trending Movies",
    "Top Rated Movies",
    "Upcoming Movies",
    "Now Playing Movies",
    "Popular Movies",
    "Popular International Movies",
    "Top Rated International Movies",
    "Upcoming International Movies"
];
const tvCharts = [
    "Trending TV Shows",
    "Top Rated TV Shows",
    "Airing Today",
    "On The Air",
    "Popular TV Shows",
    "Popular International TV Shows",
    "Top Rated International TV Shows",
    "Upcoming International TV Shows"
];
const animeCharts = [
    "Popular Anime",
    "Top Rated Anime",
    "Airing Now",
    "Upcoming Anime",
    "All Time Classics",
    "Popular International Anime",
    "Top Rated International Anime",
    "Upcoming International Anime"
];
const cartoonCharts = [
    "Popular Cartoons",
    "Top Rated Cartoons",
    "Kids Favorites",
    "Family Friendly",
    "Popular International Cartoons",
    "Top International Cartoons",
    "Upcoming International"
];
}),
"[project]/src/lib/utils/chart-slugs.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "chartNameToSlug",
    ()=>chartNameToSlug,
    "chartNames",
    ()=>chartNames,
    "chartSlugs",
    ()=>chartSlugs,
    "getChartNameFromSlug",
    ()=>getChartNameFromSlug
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/constants/genres.const.ts [app-rsc] (ecmascript)");
;
const chartNames = [
    ...__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["movieCharts"],
    ...__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["tvCharts"],
    ...__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["animeCharts"],
    ...__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cartoonCharts"]
];
function chartNameToSlug(name) {
    return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}
const slugToName = new Map(chartNames.map((name)=>[
        chartNameToSlug(name),
        name
    ]));
function getChartNameFromSlug(slug) {
    return slugToName.get(slug);
}
const chartSlugs = chartNames.map(chartNameToSlug);
}),
"[project]/src/lib/utils/charts-mapping.ts [app-rsc] (ecmascript) <locals>", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "chartFetchers",
    ()=>chartFetchers,
    "chartSectionsConfig",
    ()=>chartSectionsConfig,
    "getChartCategory",
    ()=>getChartCategory,
    "normalizeChartItems",
    ()=>normalizeChartItems
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/constants/genres.const.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/api/tmdb-client.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$utils$2f$chart$2d$slugs$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/utils/chart-slugs.ts [app-rsc] (ecmascript)");
;
;
const chartSectionsConfig = [
    {
        title: 'Movie Charts',
        charts: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["movieCharts"]
    },
    {
        title: 'TV Charts',
        charts: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["tvCharts"]
    },
    {
        title: 'Anime Charts',
        charts: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["animeCharts"]
    },
    {
        title: 'Cartoon Charts',
        charts: __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cartoonCharts"]
    }
];
const chartCategoryMap = new Map();
__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["movieCharts"].forEach((name)=>chartCategoryMap.set(name, 'movie'));
__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["tvCharts"].forEach((name)=>chartCategoryMap.set(name, 'tv'));
__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["animeCharts"].forEach((name)=>chartCategoryMap.set(name, 'anime'));
__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$constants$2f$genres$2e$const$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["cartoonCharts"].forEach((name)=>chartCategoryMap.set(name, 'cartoon'));
const chartFetchers = {
    'Trending Movies': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getTrendingMovies"])(page),
    'Top Rated Movies': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getTopRatedMovies"])(page),
    'Upcoming Movies': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getUpcomingMovies"])(page),
    'Now Playing Movies': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getNewReleases"])(page),
    'Popular Movies': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getPopularMovies"])(page),
    'Trending TV Shows': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getTrendingTVShows"])(page),
    'Top Rated TV Shows': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getTopRatedShows"])(page),
    'Airing Today': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getAiringTodayShows"])(page),
    'On The Air': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getUpcomingShows"])(page),
    'Popular TV Shows': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getPopularTVShows"])(page),
    'Popular International TV Shows': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getPopularTVShows"])(page),
    'Top Rated International TV Shows': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getTopRatedShows"])(page),
    'Upcoming International TV Shows': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getUpcomingShows"])(page),
    'Popular Anime': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getPopularAnimeShows"])(page),
    'Top Rated Anime': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getTopRatedAnimeShows"])(page),
    'Airing Now': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getAiringNowAnimeShows"])(page),
    'Upcoming Anime': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getUpcomingAnimeShows"])(page),
    'All Time Classics': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getClassicAnimeShows"])(page),
    'Popular International Anime': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getPopularAnimeShows"])(page),
    'Top Rated International Anime': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getTopRatedAnimeShows"])(page),
    'Upcoming International Anime': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getUpcomingAnimeShows"])(page),
    'Popular Cartoons': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getPopularCartoonShows"])(page),
    'Top Rated Cartoons': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getTopRatedCartoonShows"])(page),
    'Kids Favorites': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getKidsFavoriteCartoons"])(page),
    'Family Friendly': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getFamilyCartoonShows"])(page),
    'Popular International Cartoons': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getPopularCartoonShows"])(page),
    'Top International Cartoons': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getTopRatedCartoonShows"])(page),
    'Upcoming International': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getUpcomingCartoons"])(page),
    'Popular International Movies': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getPopularMovies"])(page),
    'Top Rated International Movies': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getTopRatedMovies"])(page),
    'Upcoming International Movies': (page)=>(0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["getUpcomingMovies"])(page)
};
;
function getChartCategory(chartName) {
    return chartCategoryMap.get(chartName) ?? 'movie';
}
function resolveMediaType(item, fallback) {
    const isMovie = 'title' in item && typeof item.title === 'string';
    if (isMovie) {
        return 'movie';
    }
    if (fallback === 'anime' || fallback === 'cartoon') {
        return fallback;
    }
    return 'tv';
}
function normalizeChartItems(results, fallback = 'movie') {
    return results.map((item)=>{
        const title = 'title' in item && item.title ? item.title : 'name' in item ? item.name : undefined;
        const dateValue = 'release_date' in item ? item.release_date : 'first_air_date' in item ? item.first_air_date : undefined;
        const year = dateValue ? new Date(dateValue).getFullYear() : undefined;
        const voteAverage = Number.isFinite(item.vote_average) ? item.vote_average : 0;
        const mediaType = resolveMediaType(item, fallback);
        return {
            id: item.id,
            title: title ?? 'Untitled',
            overview: item.overview ?? '',
            posterPath: item.poster_path ?? null,
            year,
            voteAverage,
            mediaType
        };
    });
}
}),
"[project]/src/components/common/Main.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
;
const Main = ({ children, className = '', ...props })=>/*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("main", {
        className: `max-w-6xl mx-auto ${className}`,
        ...props,
        children: children
    }, void 0, false, {
        fileName: "[project]/src/components/common/Main.tsx",
        lineNumber: 9,
        columnNumber: 3
    }, ("TURBOPACK compile-time value", void 0));
const __TURBOPACK__default__export__ = Main;
}),
"[project]/src/components/common/Header.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
;
const Header = ({ children, className = '', ...props })=>/*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("header", {
        className: className,
        ...props,
        children: children
    }, void 0, false, {
        fileName: "[project]/src/components/common/Header.tsx",
        lineNumber: 9,
        columnNumber: 3
    }, ("TURBOPACK compile-time value", void 0));
const __TURBOPACK__default__export__ = Header;
}),
"[project]/src/app/browse/search/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>SearchPage,
    "dynamic",
    ()=>dynamic
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$app$2d$dir$2f$link$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/client/app-dir/link.react-server.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$browse$2f$search$2f$SearchResultsContent$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/app/browse/search/SearchResultsContent.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/api/tmdb-client.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$utils$2f$charts$2d$mapping$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/src/lib/utils/charts-mapping.ts [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$common$2f$Main$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/common/Main.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$common$2f$Header$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/common/Header.tsx [app-rsc] (ecmascript)");
;
;
;
;
;
;
;
const dynamic = 'force-dynamic';
async function SearchPage({ searchParams }) {
    const params = await searchParams;
    const queryParam = params.q ?? '';
    const query = queryParam.trim();
    let initialItems = [];
    if (query) {
        const results = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$api$2f$tmdb$2d$client$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["searchTitles"])(query, 1);
        initialItems = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$utils$2f$charts$2d$mapping$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__["normalizeChartItems"])(results, 'tv');
    }
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
        className: "mt-20 px-6 py-16",
        children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$common$2f$Main$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
            className: "space-y-8",
            children: [
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
                    className: "flex items-center gap-4",
                    children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$app$2d$dir$2f$link$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                        href: "/",
                        className: "text-sm text-white/70 hover:text-white transition-colors",
                        children: "← Back to Home"
                    }, void 0, false, {
                        fileName: "[project]/src/app/browse/search/page.tsx",
                        lineNumber: 32,
                        columnNumber: 11
                    }, this)
                }, void 0, false, {
                    fileName: "[project]/src/app/browse/search/page.tsx",
                    lineNumber: 31,
                    columnNumber: 9
                }, this),
                /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$common$2f$Header$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                    className: "space-y-2",
                    children: [
                        /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("h1", {
                            className: "text-4xl font-bold text-white",
                            children: "Search"
                        }, void 0, false, {
                            fileName: "[project]/src/app/browse/search/page.tsx",
                            lineNumber: 40,
                            columnNumber: 11
                        }, this),
                        query ? /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                            className: "text-gray-300",
                            children: [
                                'Results for "',
                                query,
                                '"'
                            ]
                        }, void 0, true, {
                            fileName: "[project]/src/app/browse/search/page.tsx",
                            lineNumber: 42,
                            columnNumber: 13
                        }, this) : /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("p", {
                            className: "text-gray-300",
                            children: "Start typing in the search bar to discover movies and shows."
                        }, void 0, false, {
                            fileName: "[project]/src/app/browse/search/page.tsx",
                            lineNumber: 44,
                            columnNumber: 13
                        }, this)
                    ]
                }, void 0, true, {
                    fileName: "[project]/src/app/browse/search/page.tsx",
                    lineNumber: 39,
                    columnNumber: 9
                }, this),
                query ? /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$app$2f$browse$2f$search$2f$SearchResultsContent$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
                    initialItems: initialItems,
                    query: query
                }, void 0, false, {
                    fileName: "[project]/src/app/browse/search/page.tsx",
                    lineNumber: 48,
                    columnNumber: 11
                }, this) : null
            ]
        }, void 0, true, {
            fileName: "[project]/src/app/browse/search/page.tsx",
            lineNumber: 30,
            columnNumber: 7
        }, this)
    }, void 0, false, {
        fileName: "[project]/src/app/browse/search/page.tsx",
        lineNumber: 29,
        columnNumber: 5
    }, this);
}
}),
"[project]/src/app/browse/search/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/browse/search/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__3fd46e18._.js.map