// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth/account" | "/browse/genres/[type]/[genre]" | "/browse/home" | "/browse/library" | "/browse/library/charts/[chart]" | "/browse/search" | "/login" | "/signup" | "/title/[type]/[id]"
type AppRouteHandlerRoutes = "/api/v1/auth/signup" | "/api/v1/charts" | "/api/v1/data" | "/api/v1/episodes" | "/api/v1/genres" | "/api/v1/recommendations" | "/api/v1/search" | "/api/v1/trailers" | "/api/v1/users" | "/api/v1/users/login" | "/api/v1/users/me"
type PageRoutes = never
type LayoutRoutes = "/" | "/auth" | "/login" | "/signup"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/v1/auth/signup": {}
  "/api/v1/charts": {}
  "/api/v1/data": {}
  "/api/v1/episodes": {}
  "/api/v1/genres": {}
  "/api/v1/recommendations": {}
  "/api/v1/search": {}
  "/api/v1/trailers": {}
  "/api/v1/users": {}
  "/api/v1/users/login": {}
  "/api/v1/users/me": {}
  "/auth": {}
  "/auth/account": {}
  "/browse/genres/[type]/[genre]": { "type": string; "genre": string; }
  "/browse/home": {}
  "/browse/library": {}
  "/browse/library/charts/[chart]": { "chart": string; }
  "/browse/search": {}
  "/login": {}
  "/signup": {}
  "/title/[type]/[id]": { "type": string; "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/auth": never
  "/login": never
  "/signup": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
