// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(details)/title/[type]/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/title/[type]/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(details)/title/[type]/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/account">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/browse/genres/[type]/[genre]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/browse/genres/[type]/[genre]">> = Specific
  const handler = {} as typeof import("../../../src/app/browse/genres/[type]/[genre]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/browse/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/browse/home">> = Specific
  const handler = {} as typeof import("../../../src/app/browse/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/browse/library/charts/[chart]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/browse/library/charts/[chart]">> = Specific
  const handler = {} as typeof import("../../../src/app/browse/library/charts/[chart]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/browse/library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/browse/library">> = Specific
  const handler = {} as typeof import("../../../src/app/browse/library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/browse/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/browse/search">> = Specific
  const handler = {} as typeof import("../../../src/app/browse/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/charts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/charts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/charts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/data">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/episodes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/episodes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/episodes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/genres/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/genres">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/genres/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/recommendations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/trailers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/trailers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/trailers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/users/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/users/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/users/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/users/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/users/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/users/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/v1/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/v1/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/signup/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/signup/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
